### ISSUE TITLE
哥们有论文吗 留个联系方式 有偿

### ISSUE THREAD

**Issue by DaMi521** [MiloTnT/gym-management-system#1]

**Comment by MiloTnT** [comment]
我不是论文代做，不好意思

**Comment by DaMi521** [comment]
我是想借鉴一下你之前的毕业论文去画图 不需要代做 有的话帮我找找你的 没有的话也没事 谢谢你

**Comment by MiloTnT** [comment]
留个邮箱，我发给你

**Comment by DaMi521** [comment]
821534756@qq.com 非常感谢 因为基础薄弱 非常感谢

**Comment by MiloTnT** [comment]
> [821534756@qq.com](mailto:821534756@qq.com) 非常感谢 因为基础薄弱 非常感谢

已发送，加油！
